name: linux
on: push


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2
          - name: Set env
            run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          - name: Test
            run: echo $GITHUB_SHA_SHORT
          - uses: oprypin/find-latest-tag@v1
            with:
                repository: octokit/rest.js  # The repository to scan.
                releases-only: true  # We know that all relevant tags have a GitHub release for them.
            id: octokit  # The step ID to refer to later.
    
          - run: |
            

              wget  github.com/stupid-kid-af/godot-nighly-builds/releases/download/${TAGNAME}/godot_binaries-times${TAGNAME}.zip 


